version: '3.9'

services:
  # --- FastAPI Microservices ---
  auth-service:
    image: aniketsinare/auth-service:latest
    container_name: auth-service
    ports:
      - "8001:8001"
    restart: always

  admin-service:
    image: aniketsinare/admin-service:latest
    container_name: admin-service
    ports:
      - "8002:8002"
    restart: always

  # --- NGINX Gateway ---
  nginx-gateway:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - admin-service
    restart: always
